# Generated by Django 4.2.23 on 2025-07-08 16:00

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="invite_code",
            field=models.CharField(
                default=users.utils.get_random_code, max_length=6, unique=True
            ),
        ),
    ]
