# Generated by Django 4.2.23 on 2025-07-08 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smscode",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
